name: CICD

on: push

jobs:
  build_job: 
   runs-on: ubuntu-latest
   steps:
   - name: Run many steps
     run: echo "build job"
  
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run the steps
      run: echo "Running Tests" 

  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run many tests
      run: echo "Deploy Job" 

   
